#!/bin/sh

DAEMON="aesdsocket"

if [ "$1" = "start" ]; then
    aesdsocket -d
    exit $?
fi

if [ "$1" = "stop" ]; then
    PID=$(ps aux | grep "$DAEMON" | grep -v grep | awk '{print $1}')

    if [ -z "$PID" ]; then
        echo "Processo '$DAEMON' não encontrado."
        exit 1
    fi

    kill -s 15 $PID

    if [ $? -eq 0 ]; then
        echo "Sinal SIGTERM enviado para o processo '$DAEMON' (PID: $PID)."
        exit 0
    fi

    exit $?
fi

exit 1
